### PR TITLE
test: hardhat compatibility

### PR DESCRIPTION
**Pull request by banteg**
We had a fix for mismatching `chain.id` and `chainid()` (1337 vs 1) in ganache, but hardhat doesn't have this problem (both are 31337). This change only applies the fix for ganache. This only affects `permit` tests.

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Comment by banteg** [comment]
Don't merge yet, there are a few more fixes coming.

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
I don't know why I approved this twice lol

**Comment by banteg** [comment]
All tests pass with `hardhat@dtt.1` and https://github.com/eth-brownie/brownie/pull/1043.
```
617 passed in 1824.73s (0:30:24)
```

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
Approved a third time for the charm

**Pull request merged**
