### PR TITLE
fix: flash deposit withdraw

### PR DESCRIPTION
**Pull request by zgfzgf**
#376 
@steffenix say:“
Take a flash loan
Make deposit
Call report
Make a withdrawal
Repay the flash loan
”

### CODE REVIEW

**Comment by steffenix** [comment]
No fund locks please.

**Comment by steffenix** [comment]
One more thing, this is still a invalid protection, one user can do any number of deposits just under the `minLockedAmount`.

**Comment by zgfzgf** [comment]
> One more thing, this is still a invalid protection, one user can do any number of deposits just under the `minLockedAmount`.

Yes. Just be relatively safe. 
when minLockedAmoun = 0. all deposit locked.
It's just an implementation to solve the problem. @steffenix @fubuloubu

**Comment by fubuloubu** [comment]
At first glance this doesn't appear very sybil resistant. You can have multiple flashloans for multiple deposits and bypass this check.

**Pull request closed without merging**
