### PR TITLE
fix: strategy performance fee

### PR DESCRIPTION
**Pull request by zgfzgf**
assert performanceFee <= MAX_BPS - self.performanceFee 
change to
assert performanceFee <= MAX_BPS / 2

### CODE REVIEW

**Comment by zgfzgf** [comment]
@fubuloubu merge first. test_fee may influence #361

**Comment by fubuloubu** [comment]
I'm confused, @steffenix isn't this change already applied?

**Comment by zgfzgf** [comment]
see #347 @fubuloubu

**Comment by steffenix** [comment]
We did add it to addStrategy and `setManagementFee` but forgot that last one

**Review by steffenix — APPROVED** [review]

**Pull request merged**
