### PR TITLE
fix: explicitly add Vaults to Registry

### LINKED ISSUE #179: First vault added to release a new apiVersion is always endorsed
copied from https://github.com/iearn-finance/yearn-protocol/issues/96 by @fameal

### What's your issue about?
The vault that is used to create a new release using YRegistry.newRelease(0x...) is automatically endorsed and shown on Yearn's main site in the production tab.

**Steps to reproduce**
Create a new release using YRegistry.newRelease(0x...) with any vault.

**What is expected to happen.**
It's expected to create a new release and add the vault to the registry. 

**What actually happens.**
It creates a new release, adds the vault to the registry, and endorses it automatically.

**Notes**
It's not always that the first vault of a new release is production-ready. So we need a way to create a new release, add a vault, and test it accordingly.

### PR DESCRIPTION
**Pull request by steffenix**
fix #179

### CODE REVIEW

**Review by fubuloubu — CHANGES_REQUESTED** [review]
Blocked on https://github.com/iearn-finance/yearn-vaults/issues/189#issuecomment-776066901

**Comment by steffenix** [comment]
Can this be merge without the changes on #189 ?

**Comment by fubuloubu** [comment]
> Can this be merge without the changes on #189 ?

There's no point in merging this until we are ready to re-release the Registry

**Comment by fubuloubu** [comment]
Rebase this on master

**Review by fubuloubu — APPROVED** [review]

**Review by dougstorm — APPROVED** [review]
LGTM!

**Pull request merged**
