### PR TITLE
feat: slither CI

### PR DESCRIPTION
**Pull request by sambacha**
- adds slither github action
- updates nodejs to 14

- closes https://github.com/yearn/yearn-vaults/pull/473
- https://github.com/yearn/yearn-vaults/issues/478

- https://github.com/yearn/yearn-vaults/pull/520

### CODE REVIEW

**Comment by sambacha** [comment]
> Any reasons for updating node on this PR?

nodejs 12 is no longer supported for security patches, as is v1 of GitHub actions as well

**Comment by pandadefi** [comment]
@sambacha ping

**Comment by sambacha** [comment]
> @sambacha ping

running meow

**Comment by pandadefi** [comment]
@sambacha still not working.

**Comment by pandadefi** [comment]
There is nothing left on this PR @sambacha I will close it

**Comment by sambacha** [comment]
oops forgot to push 1 sec

**Comment by sambacha** [comment]
we gucci @pandadefi

**Comment by pandadefi** [comment]
I don't think you have to do all the setup before.
https://github.com/yearn/veYfi/blob/master/.github/workflows/slither.yaml

**Comment by sambacha** [comment]
> I don't think you have to do all the setup before. [yearn/veYfi@`master`/.github/workflows/slither.yaml](https://github.com/yearn/veYfi/blob/master/.github/workflows/slither.yaml)

I went ahead and removed the superfluous actions. 

Additionally added some workflow checks

**Comment by sambacha** [comment]
seems like we hit a rate limit via brownie:

```sh
File "brownie/project/main.py", line 921, in _get_download_url_from_tag
    raise ConnectionError(msg)
ConnectionError: Status 403 when getting package versions from Github: 'API rate limit exceeded for 52.167.154.76. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)'

Missing or forbidden.

If this issue persists, generate a Github API token and store it as the environment variable `GITHUB_TOKEN`:
[github.blog/2013-05-16-personal-api-tokens](https://github.blog/2013-05-16-personal-api-tokens/)
Error: Process completed with exit code 1.
```

**Comment by sambacha** [comment]
> I don't think you have to do all the setup before. [yearn/veYfi@`master`/.github/workflows/slither.yaml](https://github.com/yearn/veYfi/blob/master/.github/workflows/slither.yaml)

lets get this merged mate

**Comment by pandadefi** [comment]
went for https://github.com/yearn/yearn-vaults/pull/520

**Pull request closed without merging**
