### PR TITLE
fix: storage management debt

### PR DESCRIPTION
**Pull request by zgfzgf**
#354
add var managementDebt

step 1: implementation
step 2: fix old tests
step 3: add new tests

### CODE REVIEW

**Comment by zgfzgf** [comment]
I don't know why it's wrong

**Comment by steffenix** [comment]
management_fee can be assets without gains, it's not based on strategy performance but vault managed assets.

What is the idea behind these changes?

Like @fubuloubu said `Usually, I don't like to add new storage variables without a good reason why they are needed`

**Comment by zgfzgf** [comment]
block 1000, block 2000, block 3000  harvest
may block 2000 harvest. active exec management fee < receivable management fee.   debt=receivable - exec
block 3000 may pay debt

**Comment by steffenix** [comment]
> block 1000, block 2000, block 3000 harvest
> may block 2000 harvest. active exec management fee < receivable management fee. debt=receivable - exec
> block 3000 may pay debt

Most likely it will never be the case, management Fee is 2% annualized and assigned to Treasury. If that ever becomes an issue that vault management fee is at loss we will reconsider.

**Comment by fubuloubu** [comment]
> I don't understand what your needs are?

Yes, I think there is some miscommunication, I am not sure what the issue you were trying to solve is.

**Comment by zgfzgf** [comment]
> > I don't understand what your needs are?
> 
> Yes, I think there is some miscommunication, I am not sure what the issue you were trying to solve is.

first, I think #366 #345 is OK. you said:"This method also assesses the management fee, which is being skipped by this update"
so add var managementDebt

**Pull request closed without merging**
